version: '3.7'

networks:
  users-network:
    driver: bridge

services:
  users_db:
    image: mongo
    container_name: users_db
    hostname: users_db
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    environment:
      - MONGO_INITDB_DATABASE=users_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - users-network
