version: '3.7'

networks:
  users-network:
    driver: bridge
  verification_tokens-network:
    driver: bridge
  lists-network:
    driver: bridge

services:
  users_db:
    image: mongo
    container_name: users_db
    hostname: users_db
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    environment:
      - MONGO_INITDB_DATABASE=users_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - users-network

  verification_tokens_db:
    image: mongo
    container_name: verification_tokens_db
    hostname: verification_tokens_db
    ports:
      - 27117:27017
      - 27118:27018
      - 27119:27019
    environment:
      - MONGO_INITDB_DATABASE=verification_tokens_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - verification_tokens-network


  lists_db:
    image: mysql:8
    container_name: lists_db
    hostname: lists_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=lists_fb
      - MYSQL_ROOT_PASSWORD=${MYSQL_LIST_ROOT_PASS}
      - MYSQL_USER=${MYSQL_LIST_USER}
      - MYSQL_PASSWORD=${MYSQL_LIST_PASS}
    networks:
      - lists-network