spring:
  application:
    name: zuul-server
  cloud:
    config:
      uri: http://config-server:8888
      discovery:
        enabled: true
        service-id: zuul-server
      fail-fast: true
      retry:
        initial-interval: 1500
        multiplier: 1.5
        max-attempts: 10000
        max-interval: 1000

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka/}
zuul:
  routes:
    security:
      service-id: oauth-service
      path: /api/v1/security/**
      sensitive-headers: Cookie, Set-Cookie

    users:
      service-id: user-service
      path: /api/users/v1/**
